apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedemo
  labels:
    app: nodedemo
spec:
  selector:
    matchLabels:
      app: nodedemo
  replicas: 2
  template:
    metadata:
      labels:
        app: nodedemo
    spec:
      containers:
      - name: nodedemo
        image: kfirdado/nodedemo
        # livenessProbe:
        #   httpGet:
        #     path: /index.html
        #     port: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /index.html
        #     port: 8080
        env:
        - name: REDISHOST
          value: "$(REDISSERVICE).$(REDISNAMESPACE):6379"
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodedemo
  labels:
    app: nodedemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nodedemo
